sudo: required
services:
  - docker

before_install:
  - docker build -t mizzomazzo/react -f Dockerfile.dev .

script:
  - docker run -e CI=true mizzomazzo/react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-2-427092324598"
  bucket_path: "react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
