sudo: required
services:
  - docker

before_install:
  - docker build -t mizzomazzo/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mizzomazzo/client-test npm run test

after_success:
  - docker build -t mizzomazzo/dockercourse-client ./client
  - docker build -t mizzomazzo/dockercourse-nginx ./nginx
  - docker build -t mizzomazzo/dockercourse-server ./server
  - docker build -t mizzomazzo/dockercourse-worker ./worker

#push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #login to docker
  - docker push mizzomazzo/dockercourse-client
  - docker push mizzomazzo/dockercourse-nginx
  - docker push mizzomazzo/dockercourse-server
  - docker push mizzomazzo/dockercourse-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "react"
#  env: "React-env"
#  bucket_name: "elasticbeanstalk-us-east-2-427092324598"
#  bucket_path: "react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
