version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app

#tests can be configured inside the yml but there is no perfect way
#  tests:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - /app/node_modules
#      - .:/app
#    command: ["npm", "run", "test"]
